version: "3"
services:
    web:
      container_name: app-serviciosocial-node
      image: app-serviciosocial-node
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      environment: 
        - NODE_ENV=$NODE_ENV
        - MONGO=$MONGO
        - MONGO_DB_NAME=$MONGO_DB_NAME
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
      ports:
        - "8090:3000"
      links: 
        - database
      volumes: 
        - .:/usr/src/app
    database:
      container_name: app-serviciosocial-mongo
      image: mongo
      env_file: .env
      environment: 
        - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        - MONGO_INITDB_DATABASE=$MONGO_DB_NAME
      ports: 
        - "8091:27017"
      volumes:
        #- dbdata:/data/db
        - ./mongo/config.sh:/docker-entrypoint-initdb.d/config.sh
#volumes:
    #dbdata:
